dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - node

before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"

before_script:
  - npm install -g --silent @angular/cli
  - cd dps-frontend
  - npm install
  - ng test --single-run

script:
  - ng build --prod

notifications:
  slack: csc434:69KLuLQ6IsZkW1lTmG1hFJtY