language: node_js

node_js:
  - node

before_script:
  - npm install -g --silent @angular/cli
  - cd dps-frontend
  - npm install
  - ng test --single-run

script:
  - ng build --prod

notifications:
  slack: csc434:69KLuLQ6IsZkW1lTmG1hFJtY