dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - node

before_install:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'

before_script:
  - npm install -g --silent @angular/cli
  - cd dps-frontend
  - npm install
  - ng test --single-run

script:
  - ng build --prod

notifications:
  slack: csc434:69KLuLQ6IsZkW1lTmG1hFJtY